### ISSUE TITLE
Binary file

### ISSUE THREAD

**Issue by temaivanoff** [thegrandpoobah/dsgrab#13]
Hi, url not working, please put binary file to release.

**Comment by thegrandpoobah** [comment]
I put the binary here: https://github.com/thegrandpoobah/dsgrab/releases/download/V1.6.0/DSGrab.1.6.0.exe .. this is the last working version that I have on hand which is from 2013, so there might be a couple hoops that you'll need to jump through to get it actually working. But hopefully its a starting point.
